# Generated by Django 4.1 on 2022-09-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='sales_contract',
            new_name='sales_contact',
        ),
    ]
